[2022-06-20 06:37:38,882] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available manual__2022-06-20T06:37:35.018175+00:00 [queued]>
[2022-06-20 06:37:38,904] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available manual__2022-06-20T06:37:35.018175+00:00 [queued]>
[2022-06-20 06:37:38,905] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:37:38,906] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-20 06:37:38,908] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:37:38,940] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-06-20 06:37:35.018175+00:00
[2022-06-20 06:37:38,952] {standard_task_runner.py:52} INFO - Started process 235 to run task
[2022-06-20 06:37:38,966] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dags_new_version', 'is_api_available', 'manual__2022-06-20T06:37:35.018175+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/user.py', '--cfg-path', '/tmp/tmpkq0f7d59', '--error-file', '/tmp/tmp5psamn2m']
[2022-06-20 06:37:38,968] {standard_task_runner.py:80} INFO - Job 177: Subtask is_api_available
[2022-06-20 06:37:39,199] {task_command.py:370} INFO - Running <TaskInstance: dags_new_version.is_api_available manual__2022-06-20T06:37:35.018175+00:00 [running]> on host ca3ce831c04f
[2022-06-20 06:37:39,454] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dags_new_version
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T06:37:35.018175+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-20T06:37:35.018175+00:00
[2022-06-20 06:37:39,459] {http.py:97} INFO - Poking: api/
[2022-06-20 06:37:39,484] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-06-20 06:37:39,498] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-06-20 06:37:40,324] {base.py:301} INFO - Success criteria met. Exiting.
[2022-06-20 06:37:40,368] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dags_new_version, task_id=is_api_available, execution_date=20220620T063735, start_date=20220620T063738, end_date=20220620T063740
[2022-06-20 06:37:40,450] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 06:37:40,554] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
