[2022-06-17 09:54:30,774] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available manual__2022-06-17T09:54:16.978802+00:00 [queued]>
[2022-06-17 09:54:30,812] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available manual__2022-06-17T09:54:16.978802+00:00 [queued]>
[2022-06-17 09:54:30,816] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 09:54:30,819] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-17 09:54:30,820] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 09:54:30,848] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-06-17 09:54:16.978802+00:00
[2022-06-17 09:54:30,859] {standard_task_runner.py:52} INFO - Started process 5772 to run task
[2022-06-17 09:54:30,877] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dags_new_version', 'is_api_available', 'manual__2022-06-17T09:54:16.978802+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/user.py', '--cfg-path', '/tmp/tmp1wf0kyl_', '--error-file', '/tmp/tmpmal8lu4w']
[2022-06-17 09:54:30,880] {standard_task_runner.py:80} INFO - Job 143: Subtask is_api_available
[2022-06-17 09:54:31,018] {task_command.py:370} INFO - Running <TaskInstance: dags_new_version.is_api_available manual__2022-06-17T09:54:16.978802+00:00 [running]> on host adccabfb4a32
[2022-06-17 09:54:32,231] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dags_new_version
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T09:54:16.978802+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T09:54:16.978802+00:00
[2022-06-17 09:54:32,234] {http.py:97} INFO - Poking: api/
[2022-06-17 09:54:32,402] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-06-17 09:54:32,461] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-06-17 09:54:33,374] {base.py:301} INFO - Success criteria met. Exiting.
[2022-06-17 09:54:33,596] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dags_new_version, task_id=is_api_available, execution_date=20220617T095416, start_date=20220617T095430, end_date=20220617T095433
[2022-06-17 09:54:33,828] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-17 09:54:35,079] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
