[2022-06-12 07:22:50,535] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-06-12T07:22:38.940831+00:00 [queued]>
[2022-06-12 07:22:50,564] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-06-12T07:22:38.940831+00:00 [queued]>
[2022-06-12 07:22:50,566] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 07:22:50,567] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 07:22:50,571] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 07:22:50,626] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-06-12 07:22:38.940831+00:00
[2022-06-12 07:22:50,641] {standard_task_runner.py:52} INFO - Started process 9167 to run task
[2022-06-12 07:22:50,656] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-06-12T07:22:38.940831+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmp9xhekyk7', '--error-file', '/tmp/tmp_auwn3h7']
[2022-06-12 07:22:50,659] {standard_task_runner.py:80} INFO - Job 15: Subtask inaccurate
[2022-06-12 07:22:51,036] {task_command.py:370} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-06-12T07:22:38.940831+00:00 [running]> on host f95f507e9417
[2022-06-12 07:22:51,405] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T07:22:38.940831+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-12T07:22:38.940831+00:00
[2022-06-12 07:22:51,411] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-12 07:22:51,420] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-12 07:22:51,501] {subprocess.py:85} INFO - Output:
[2022-06-12 07:22:51,515] {subprocess.py:92} INFO - inaccurate
[2022-06-12 07:22:51,517] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-12 07:22:51,611] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220612T072238, start_date=20220612T072250, end_date=20220612T072251
[2022-06-12 07:22:51,715] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-12 07:22:51,943] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
