[2022-06-20 06:37:05,307] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available scheduled__2022-06-19T00:00:00+00:00 [queued]>
[2022-06-20 06:37:05,648] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dags_new_version.is_api_available scheduled__2022-06-19T00:00:00+00:00 [queued]>
[2022-06-20 06:37:05,649] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:37:05,652] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-20 06:37:05,654] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:37:05,882] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-06-19 00:00:00+00:00
[2022-06-20 06:37:05,937] {standard_task_runner.py:52} INFO - Started process 201 to run task
[2022-06-20 06:37:05,981] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dags_new_version', 'is_api_available', 'scheduled__2022-06-19T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/user.py', '--cfg-path', '/tmp/tmpzpvv27d8', '--error-file', '/tmp/tmpbgs2pgbo']
[2022-06-20 06:37:05,983] {standard_task_runner.py:80} INFO - Job 169: Subtask is_api_available
[2022-06-20 06:37:06,781] {task_command.py:370} INFO - Running <TaskInstance: dags_new_version.is_api_available scheduled__2022-06-19T00:00:00+00:00 [running]> on host ca3ce831c04f
[2022-06-20 06:37:07,565] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dags_new_version
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-06-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-19T00:00:00+00:00
[2022-06-20 06:37:07,570] {http.py:97} INFO - Poking: api/
[2022-06-20 06:37:07,641] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-06-20 06:37:07,647] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-06-20 06:37:08,660] {base.py:301} INFO - Success criteria met. Exiting.
[2022-06-20 06:37:08,945] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dags_new_version, task_id=is_api_available, execution_date=20220619T000000, start_date=20220620T063705, end_date=20220620T063708
[2022-06-20 06:37:09,520] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 06:37:10,382] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
