[2022-06-12 10:00:03,587] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-06-12T09:59:50.466895+00:00 [queued]>
[2022-06-12 10:00:03,621] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-06-12T09:59:50.466895+00:00 [queued]>
[2022-06-12 10:00:03,623] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 10:00:03,625] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 10:00:03,628] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 10:00:03,684] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-06-12 09:59:50.466895+00:00
[2022-06-12 10:00:03,706] {standard_task_runner.py:52} INFO - Started process 10375 to run task
[2022-06-12 10:00:03,741] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-06-12T09:59:50.466895+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmptxc3xuob', '--error-file', '/tmp/tmpuyd5akhf']
[2022-06-12 10:00:03,749] {standard_task_runner.py:80} INFO - Job 20: Subtask inaccurate
[2022-06-12 10:00:04,408] {task_command.py:370} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-06-12T09:59:50.466895+00:00 [running]> on host f95f507e9417
[2022-06-12 10:00:04,739] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T09:59:50.466895+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-12T09:59:50.466895+00:00
[2022-06-12 10:00:04,744] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-12 10:00:04,747] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-12 10:00:04,771] {subprocess.py:85} INFO - Output:
[2022-06-12 10:00:04,776] {subprocess.py:92} INFO - inaccurate
[2022-06-12 10:00:04,778] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-12 10:00:04,835] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220612T095950, start_date=20220612T100003, end_date=20220612T100004
[2022-06-12 10:00:04,870] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-12 10:00:04,922] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
